export interface TimezoneOption {
  value: string;
  label: string;
}

/** "auto" is resolved server-side to the real IANA zone for the given coordinates. */
export const AUTO_TIMEZONE = "auto";

/** Curated list of common IANA zones for the manual coordinates form. */
export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { value: AUTO_TIMEZONE, label: "Detectar automáticamente" },
  { value: "Europe/Madrid", label: "Europe/Madrid" },
  { value: "Europe/London", label: "Europe/London" },
  { value: "Europe/Lisbon", label: "Europe/Lisbon" },
  { value: "Europe/Paris", label: "Europe/Paris" },
  { value: "Europe/Berlin", label: "Europe/Berlin" },
  { value: "Europe/Rome", label: "Europe/Rome" },
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam" },
  { value: "Europe/Zurich", label: "Europe/Zurich" },
  { value: "Europe/Dublin", label: "Europe/Dublin" },
  { value: "Europe/Brussels", label: "Europe/Brussels" },
  { value: "Europe/Vienna", label: "Europe/Vienna" },
  { value: "Europe/Stockholm", label: "Europe/Stockholm" },
  { value: "Europe/Oslo", label: "Europe/Oslo" },
  { value: "Europe/Copenhagen", label: "Europe/Copenhagen" },
  { value: "Europe/Helsinki", label: "Europe/Helsinki" },
  { value: "Europe/Warsaw", label: "Europe/Warsaw" },
  { value: "Europe/Prague", label: "Europe/Prague" },
  { value: "Europe/Budapest", label: "Europe/Budapest" },
  { value: "Europe/Athens", label: "Europe/Athens" },
  { value: "Europe/Moscow", label: "Europe/Moscow" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul" },
  { value: "Atlantic/Reykjavik", label: "Atlantic/Reykjavik" },
  { value: "America/New_York", label: "America/New_York" },
  { value: "America/Chicago", label: "America/Chicago" },
  { value: "America/Denver", label: "America/Denver" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles" },
  { value: "America/Toronto", label: "America/Toronto" },
  { value: "America/Mexico_City", label: "America/Mexico_City" },
  { value: "America/Bogota", label: "America/Bogota" },
  { value: "America/Lima", label: "America/Lima" },
  { value: "America/Santiago", label: "America/Santiago" },
  { value: "America/Argentina/Buenos_Aires", label: "America/Buenos_Aires" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo" },
  { value: "America/Caracas", label: "America/Caracas" },
  { value: "Africa/Cairo", label: "Africa/Cairo" },
  { value: "Africa/Lagos", label: "Africa/Lagos" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca" },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh" },
  { value: "Asia/Dubai", label: "Asia/Dubai" },
  { value: "Asia/Tehran", label: "Asia/Tehran" },
  { value: "Asia/Karachi", label: "Asia/Karachi" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta" },
  { value: "Asia/Ho_Chi_Minh", label: "Asia/Ho_Chi_Minh" },
  { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala_Lumpur" },
  { value: "Asia/Singapore", label: "Asia/Singapore" },
  { value: "Asia/Manila", label: "Asia/Manila" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai" },
  { value: "Asia/Seoul", label: "Asia/Seoul" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo" },
  { value: "Australia/Sydney", label: "Australia/Sydney" },
  { value: "Australia/Perth", label: "Australia/Perth" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji" },
  { value: "UTC", label: "UTC" }
];
